name: Lint

on:
  push:
    paths-ignore:
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - README.md
      - 'fastlane/**'
      - .github/FUNDING.yml
  pull_request:
    paths-ignore:
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - README.md
      - 'fastlane/**'
      - .github/FUNDING.yml

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Lint checks
      run: bundle exec fastlane lint
    - name: Archive lint reports
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: lint-reports
        path: app/build/reports/*.html
