name: Run tests

on:
  push:
    paths-ignore:
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - README.md
      - 'fastlane/**'
      - .github/FUNDING.yml
  pull_request:
    paths-ignore:
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - README.md
      - 'fastlane/**'
      - .github/FUNDING.yml

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew -Pcoverage :app:jacocoTestReportGoogleplayDebug :app:createGoogleplayDebugAndroidTestCoverageReport
      - name: upload coverage
        uses: codecov/codecov-action@v3
        with:
          directory: ./app/build
